name: Clang tidy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CLANG_TIDY_VERSION: 13

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Install vcpkg packages
        run: |
         ./vcpkg/bootstrap-vcpkg.sh

      - name: Install clang-tidy
        run: |
         wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
         sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-${CLANG_TIDY_VERSION} main"
         sudo apt-get update
         sudo apt-get install -y clang-tidy-$CLANG_TIDY_VERSION
         
      - name: Create Build Environment
        run: |
          cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_CLANG_TIDY=ON -DCLANG_TIDY_VERSION=$CLANG_TIDY_VERSION

      - name: Run clang tidy
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          cmake --build . --target tidy
