name: Clang tidy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CLANG_TIDY_VERSION: 13

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Install vcpkg packages
        # vcpkg binary can only be compiled using gcc for now (bootstrap step)
        run: |
         ./vcpkg/bootstrap-vcpkg.sh
         
      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        env:
          CC: /usr/local/opt/llvm/bin/clang
          CXX: /usr/local/opt/llvm/bin/clang++
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_CLANG_TIDY=ON -DCLANG_TIDY_VERSION=$CLANG_TIDY_VERSION

      - name: Run clang tidy
        working-directory: ${{runner.workspace}}/build
        shell: bash
        env:
          CC: /usr/local/opt/llvm/bin/clang
          CXX: /usr/local/opt/llvm/bin/clang++
        run: |
          cmake --build . --target tidy
