name: MacOS / clang
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Install vcpkg packages
        # vcpkg binary can only be compiled using gcc for now (bootstrap)
        # range-v3 library is compiled from given commit with clang 13.0 libc++ compilation fix
        # sed -i '4s/.*/REF 83783f578e0e6666d68a3bf17b0038a80e62530e/' vcpkg/ports/range-v3/portfile.cmake
        # sed -i '5s/.*/SHA512 f0953e3c4e25ddf2f94b583080b8966faf1973243e01f77d23f8c04c2e0352003e4bd12490a46176472ad46c80dec99a1a8880a9bde8006eb01e3c3d8eee2fb4/' \ 
        #        vcpkg/ports/range-v3/portfile.cmake
        # ./vcpkg/vcpkg install
        run: |
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg install
           
      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        env:
          CC: /usr/local/opt/llvm/bin/clang
          CXX: /usr/local/opt/llvm/bin/clang++
        working-directory: ${{runner.workspace}}/build
        run: |
          clang --version
          clang++ --version
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE
